# SPDX-FileCopyrightText: 2022 Kent Gibson <warthog618@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[workspace]
members = [
  "lib",
  "cli",
  "uapi",
  "embedded-hal",
]

resolver = "2"
